### PR TITLE
Added support for swarm api "Node" field on container

### PR DESCRIPTION
**Pull request by urlund**
See: https://docs.docker.com/swarm/swarm-api/

### CODE REVIEW

**Comment by atroy** [comment]
LGTM

**Comment by joelwurtz** [comment]
Hey, thanks for the PR and sorry for the delay.

This library use a generation tool for the low level API, which is based on the swagger (OpenAPI) standard.

Can you edit the docker-swagger.json file as the root of the repository instead of the generated files ?

If you don't know how to do it, don't hesite to ask for help !

Thanks again,

**Comment by urlund** [comment]
Maybe you should emphasize that in "CONTRIBUTING"... (or have I missed something?)

**Comment by joelwurtz** [comment]
> Maybe you should emphasize that in "CONTRIBUTING"... (or have I missed something?)

Yes it lacks information about it, i'm actually rewriting the /containers/json /container/create part will do the change to CONTRIBUTING in a latter PR

**Comment by joelwurtz** [comment]
I make the change on 1.24 master along with all the API endpoint for Swarm, CONTRIBUTING.md has been updated to reflect how to work on this repo.

I did not tag this as i want feedback first, but you can test it by using 1.24@dev version in your composer.

Thanks for this PR, i hope the last changes will be good for you.

**Pull request closed without merging**
