### PR TITLE
PHP cs-fixer setup

### PR DESCRIPTION
**Pull request by Soullivaneuh**
The fixer is required, but never setup.

Now it is. :smile: 

Some points:

- I took benefit of not release yet version to introduce risky fixers, especially for PHP and strict typing.
- I introduced PHP 7.1 rule. So #264 must be discussed and merged before this one
- I add the `generated` folder to the configuration. This may have to be modified after #262 

I also add some rules. Feel free to comment to update/remove/add some. Here is the list: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.7/README.rst

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
```
 [Symfony\Component\Process\Exception\ProcessTimedOutException]
 The process "vendor/bin/php-cs-fixer fix --dry-run --verbose --diff" exceed
 ed the timeout of 300 seconds.
```

Well.

**Comment by joelwurtz** [comment]
Can you rebase this ? Would gladly accept

**Comment by Soullivaneuh** [comment]
@joelwurtz done!

**Comment by joelwurtz** [comment]
Thanks a lot

**Pull request merged**
