### PR TITLE
update spec and regen code

### PR DESCRIPTION
**Pull request by CliffLin**
change datetime to string
fix service find url typo

### CODE REVIEW

**Comment by leo108** [comment]
@joelwurtz Is this project still alive? This pr fixes issue https://github.com/docker-php/docker-php/issues/238

**Comment by joelwurtz** [comment]
Yes it is still alive, just have 0 time for the past months to deal with current problems. I try to merge directly if the PR is good enough, but this is not the case here.

There is the possibility to use a specific date time format in jane, it will be far better than using a string.

**Comment by CliffLin** [comment]
@joelwurtz ,
I cannot find any solution for the problem about nanoseconds format.
And I add the date-time format ``` Y-m-d\TH:i:s.uuP```, the double ```u``` is a tricky way to parse for nanosecond

**Comment by joelwurtz** [comment]
This should be good on 2.0

**Pull request closed without merging**
