### PR TITLE
Fixes some api related issues

### PR DESCRIPTION
**Pull request by atroy**
Fixes some issues related to 
- Logging
- Multihostnetwork
- Container search with containers that have portbindings defined

### CODE REVIEW

**Comment by atroy** [comment]
@joelwurtz sorry for the ping, but it would be nice to have a new version running with this ;-) Especially for people using multihostnetwork.

**Comment by joelwurtz** [comment]
Good for me :+1: 

Thanks for the awesome work !

**Comment by joelwurtz** [comment]
For the release i want to work / merge #188 before tagging a new one (ATM, you can use the -dev version of 1.22)

I will try to do this shortly (but like always will depend on my available free time :) )

**Comment by atroy** [comment]
Ok, I will work with the dev version in the mean time. I also work on some swarm related things. It would be a nice addition to your awesome work! Swarm has nearly the same api, but some additional params and methods. I will mention you in my fork if I got something useful.

**Comment by joelwurtz** [comment]
Maybe the swarm parameters / methods can be added here also ? (As long as they remain optional it should work)

Also, if you want to work more on this library, i don't mind adding people to be official contributors on docker-php.

**Comment by atroy** [comment]
Sure, we could do it that way. 

I would be glade to be an official contributor, but primary I do this work for a project we setting up in our company. So my time is also in a way limited - like yours. 
Currently our implementation highly depends on your library, and will continue in the future, so I think I can help you out in some way.

**Comment by joelwurtz** [comment]
As long as you do PR you help a lot so no worries :)

**Comment by atroy** [comment]
But you could follow me on twitter "atroy87", so we can communicate over messages.

**Pull request merged**
