### PR TITLE
Fix symfony 3.x require version strings

### PR DESCRIPTION
**Pull request by LeeSaferite**

### CODE REVIEW

**Comment by joelwurtz** [comment]
I have seen this on others projects, (however this project use the same notation than symfony), what is the difference with the current implementation ?

**Comment by hxpro** [comment]
[Versions - Composer](https://getcomposer.org/doc/articles/versions.md)

**Comment by LeeSaferite** [comment]
The one you have is locked to 3.0 exactly. But I'm running 3.0.1 and this will not install for me. The caret allows it to match later versions as well. The link provided by @hxpro explains all the specifics.

**Comment by joelwurtz** [comment]
Thanks.

**Pull request merged**
