### PR TITLE
Updates imports from OpenApi to new version

### PR DESCRIPTION
**Pull request by Tabrizian**
Hi,

The new OpenApi has some minor changes in the import path. This pull request fixes them.

Yours truly,
Iman Tabrizian

### CODE REVIEW

**Comment by joelwurtz** [comment]
Can you also update the minimum version of the jane openapi requirement in order for this to work ?

**Comment by Tabrizian** [comment]
Sure I will :)

**Comment by Tabrizian** [comment]
According to the source code of OpenApi v1.3. 

> QueryParam is deprecated since 1.3 and will be removed in 2.0, please use Joli\Jane\OpenApi\Runtime\Client\QueryParam instead.

It is since v1.3.

**Comment by joelwurtz** [comment]
Thanks !

**Pull request merged**
